{% set version = "0.0.0" %}
package:
    name: pysjef
    version: {{ version }}

source:
    path: ../

build:
#    skip: True #[win]

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake >=3.14
    host:
        - python >=3.6
        - pip
        - boost-cpp >=1.71
        - pugixml
        - cython >=0.24
        - regex
    run:
        - boost-cpp >=1.71
        - python >=3.7
        - ipython
        - pugixml
        - lxml >=4.0
        - numpy >=1.12
        - regex

test:
    imports:
        - pysjef
        - pysjef.project

about:
    license: MIT
    license_file: LICENSE
    summary: |
        Python Simple Job Execution Framework (Pysjef) is pronounced pie-chef
